//This file is generated by VisualGDB and is used to get accurate IntelliSense
#pragma once
#include <Arduino.h>

#define SYSPROGS_ARDUINO_EXPAND_GENERATED_PROTOTYPES \
	void WiFiStationConnected(system_event_id_t event, system_event_info_t info); \
	void WiFiGotIP(system_event_id_t event, system_event_info_t info); \
	void WiFiStationDisconnected(system_event_id_t event, system_event_info_t info); \
	void displayTask(void* parameters); \
	void measurementTask(void* parameters); \
	void logTask(void* parameters); \
	void myTimerCallback(TimerHandle_t xTimer); \
	bool startJob(); \
	void listDir(fs::FS &fs, const char * dirname, uint8_t levels); \
	void setup(); \
	void loop(); \

