//This file is generated by VisualGDB and is used to get accurate IntelliSense
#pragma once
#include <Arduino.h>

#define SYSPROGS_ARDUINO_EXPAND_GENERATED_PROTOTYPES \
	void onIndexRequest(AsyncWebServerRequest* request); \
	void onCSSRequest(AsyncWebServerRequest* request); \
	void onJSRequest(AsyncWebServerRequest* request); \
	void onPNGRequest(AsyncWebServerRequest* request); \
	void onDataRequest(AsyncWebServerRequest* request); \
	void onPageNotFound(AsyncWebServerRequest* request); \
	void setup(); \
	void loop(); \

