//This file is generated by VisualGDB and is used to get accurate IntelliSense
#pragma once
#include <Arduino.h>

#define SYSPROGS_ARDUINO_EXPAND_GENERATED_PROTOTYPES \
	void displayTask(void* parameters); \
	void measurementTask(void* parameters); \
	void logTask(void* parameters); \
	void setup(); \
	void loop(); \

